### ISSUE TITLE
Support for List or Details View inside of Portal.

### ISSUE THREAD

**Issue by Zyzzyvx** [Ross-Patterson/Portals-Desktop-Organization#114] opened 2023-04-12 20:02 UTC
**Is your feature request related to a problem? Please describe.**
For folders with many files inside of it, the native list or details view for folders is useful.

**Describe the solution you'd like**
The ability to default portals to a different view (e.g. list, details). It would be particularly nice if one could have a default (e.g. all portals are in list view) while also allowing different portals to deviate (e.g. this one portal is large icons).

**Comment by Ross-Patterson** [comment] 2023-04-21 17:28
Duplicate of #97

**Closed by Ross-Patterson** 2023-04-21 17:28 UTC
Labels: enhancement
