### ISSUE TITLE
the softwar lag the windows 11 right click when try it in the desktop it take a lot of time to show the right click menu

### ISSUE THREAD

**Issue by ayman3340** [Ross-Patterson/Portals-Desktop-Organization#58] opened 2022-09-29 09:15 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Ross-Patterson** [comment] 2022-10-03 09:23
Duplicate of #59

**Closed by Ross-Patterson** 2022-10-03 09:23 UTC
Labels: bug
