### ISSUE TITLE
Startup splashscreen disabled.

### ISSUE THREAD

**Issue by ak1dd** [Ross-Patterson/Portals-Desktop-Organization#203] opened 2023-11-17 07:36 UTC
I would like to be able to disable the startup splashscreen.   When I boot/start windows I have no windows popup except the Portals one.

Something like

- Launch on Startup
- Splashscreen disable on Startup
- Auto Update
- ....

**Comment by Ross-Patterson** [comment] 2023-11-18 13:09
duplicate of #177

**Closed by Ross-Patterson** 2023-11-18 13:09 UTC
Labels: enhancement
