### ISSUE TITLE
Bug - Clicking on Portal make it disappears

### ISSUE THREAD

**Issue by ongart-a** [Ross-Patterson/Portals-Desktop-Organization#28] opened 2022-06-07 06:43 UTC
When having more than one portals on the desktop, sometime clicking on the portal that was created last would make that portal disappear. This happened after user was doing something else for a while, and came back to select a file on that portal.
This would not happen on any other Portal.

This faulty behavior would go away if I opened the Portal setting windows.

Video of me clicking on the portal to make it disappears
https://photos.app.goo.gl/rAYHY3f8u46s8Yko6

**Comment by Ross-Patterson** [comment] 2022-07-13 09:50
Duplicate of #30 .

**Closed by Ross-Patterson** 2022-07-13 09:50 UTC
Labels: bug
