### ISSUE TITLE
Windows Key D not showing desktop

### ISSUE THREAD

**Issue by soopercow** [Ross-Patterson/Portals-Desktop-Organization#146] opened 2023-05-22 19:58 UTC
Windows Key D not showing desktop 

**To Reproduce**
1. Have Portals running
2. Press Win+D - nothing happens
3. Exit Portals
4. Normal Win+D behaviour restored (show/hide desktop)

**Expected behavior**
Win+D should toggle showing your desktop

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version [e.g. 3.0.1.0]

**Comment by dking02** [comment] 2023-05-23 08:39
It’s not clear from your problem description what you were expecting to happen when Win+D (Show Desktop) is pressed. I also have Portals v3.0.1 running on Windows 11 and it appears to be working as intended.

When only desktop icons and portals are present on the desktop, Win+D (Show Desktop) has no visible effect. The portals and desktop icons will remain visible. However, if you also have any application windows open, they will be minimized. This includes the Portals Setup window (aka main window) which runs as a normal application in its own window whereas the Portals systray app runs as a background process. This is what I assume is the expected (correct) behavior.

The purpose of having portals is to keep groups of icons available and controllable on the desktop. They serve a function similar to regular desktop icons and thus it is not desirable to have them affected by Win+D. If you also want to have the portals become hidden, you can follow-up the Win+D with a Ctrl+Shift+A or double-click on the desktop (requires enabling these hotkeys in the Portal Setup screen). Note that another Win+D will also not restore the portals; you need to issue another Ctrl+Shift+A or double-click to do so.

Given the lack of documentation on the program, it can be unclear in some situations what the developer intended. However, in this case, I noticed that the changelogs for both v2.1.0.5 and 2.1.0.2 refer to changes to make sure portals are not minimized when Win+D is pressed. Also see closed issue #19 (Win+D minimizes all portals) which discusses some of the implementation details for resolving the related bug.

**Comment by soopercow** [comment] 2023-05-23 08:58
> 

You make a solid point, I didn't mention what else I had running, I have Chrome and perhaps a game running and Win+D does nothing, as soon as I close Portals it behaves as you describe above

**Comment by Ross-Patterson** [comment] 2023-06-05 17:11
This is the catch-22 situation I am in. The windows APIs do not allow programs to bypass WIN+D. From Microsoft's point of view show the desktop means exactly what it says, no exceptions.

The only way to get around this is to make the child portals children of the desktop window - which has its own downsides:
https://devblogs.microsoft.com/oldnewthing/20130412-00/?p=4683

And even that seems not to be 100% consistent, although you are the only person who has reported it stopping all windows being hidden.

**Comment by soopercow** [comment] 2023-06-05 19:43
That does look like a pain, it's not consistently all windows, some times some of them minimize it's very odd. I wonder how Stardock does it with fences (assuming it works I've not used it for years).

Oh well if it can't be fixed it can't be fixed

**Comment by soopercow** [comment] 2023-06-05 19:43
That does look like a pain, it's not consistently all windows, some times some of them minimize it's very odd. I wonder how Stardock does it with fences (assuming it works I've not used it for years)

**Closed** 2023-11-30 19:18 UTC
Labels: bug
