### ISSUE TITLE
Option to Place Icons anywhere without Grid Restrictions, 

### ISSUE THREAD

**Issue by aicraglednay** [Ross-Patterson/Portals-Desktop-Organization#270] opened 2024-03-21 01:45 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Ross-Patterson** [comment] 2024-04-23 16:56
duplicate of #284

**Closed by Ross-Patterson** 2024-04-23 16:56 UTC
Labels: enhancement
