### ISSUE TITLE
FEATURE REQUEST: drag and drop files onto a directory shortcut inside of a portal

### ISSUE THREAD

**Issue by Pearism** [Ross-Patterson/Portals-Desktop-Organization#218] opened 2024-01-08 02:40 UTC
I can't drag and drop files onto a directory shortcut inside of a portal. The result is that the Directory is opened. 
While it's not the end of the world, as I can do the extra steps.. it would be very nice if this worked.

On a Desktop sites a JPG,  
I'd like to drag and drop that JPG onto a directory shortcut that is inside of a portal. 
The result would be that the dragged and dropped file would be moved to the directory if on same drive as Desktop else it would be copied to the directory.

Thank You Ross

**Comment by Ross-Patterson** [comment] 2024-01-10 20:56
This already happens:

https://github.com/Ross-Patterson/Portals-Desktop-Organization/assets/66630787/4a393df5-50eb-4e6d-bf74-e4e1f05f2551


If you are seeing something different, please provide a screen recording.

**Comment by Pearism** [comment] 2024-01-10 21:16
You dragged the file onto a Directory and not a shortcut for a directory as I had stated.

**Comment by Ross-Patterson** [comment] 2024-01-10 21:43
Ahh ok I see now - should be an easy fix.

**Comment by Pearism** [comment] 2024-01-10 21:52
You're the man! ;)

**Comment by Ross-Patterson** [comment] 2024-01-14 16:51
Closing as this is a duplicate of #212 - will continue updates there

**Closed by Ross-Patterson** 2024-01-14 16:51 UTC
Labels: enhancement
