### ISSUE TITLE
Feature request and an issue that I'm facing.

### ISSUE THREAD

**Issue by GameIT-Official** [Ross-Patterson/Portals-Desktop-Organization#77] opened 2022-12-06 17:14 UTC
Feature request: Add option for spacing between Icons it would make the fences look better

An issue that I'm facing:

Sometimes when I hover over the fences/portals the mouse pointer turns into window resize mode and the fence/portal does not open which is annoying. On stardock fences this is not an issue.
 I like your software cuz it's better has more animations and better customizability etc and I would rly like that to be fixed. I can send you a clip if you want. Edit 2: I have this issue by placing the portals a bit outside of the desktop.
Edit: and I also can't add windows Icons such as This PC, Control Panel, Recycle Bin (also the recycle bin doesn't change icons when emptied) etc

**Comment by Ross-Patterson** [comment] 2022-12-09 10:49
1st one is a duplicate of #64 

2nd one - please provide screen recording or screenshots.

3rd one - maybe create shortcuts to these, rather than dragging the links themselves. These are special system icons and not regular shortcuts I believe.
![image](https://user-images.githubusercontent.com/66630787/206685784-372fab18-33b6-4f56-b4b7-fd4f6303c549.png)

**Comment by GameIT-Official** [comment] 2022-12-09 14:18
1: when the next version with the ability to customize spacing be released?
2: I fixed this problem my placing the portals a bit outside of the desktop:

**Comment by GameIT-Official** [comment] 2022-12-09 14:24
1: when the next version with the ability to customize spacing be released?
2: When the portal is place on top the mouse pointer turns into window
resize mode, I fixed this problem my placing the portals a bit outside of
the desktop:
 portals.mp4
<https://drive.google.com/file/d/117ZzjCpOAzt6tE6hKnyUg5nehze3zKVS/view?usp=drive_web>
3: This is not an issue on stardock fences but it's fine.
Thanks for your assistance! and your cool software!

**Comment by Ross-Patterson** [comment] 2022-12-09 15:47
1. Hard to say - maybe 1 or 2 months - I am just working on this in my spare time.
2. I can't access the google drive link unfortunately - can you drag the .mp4 file directly into the comment?
3. Stardock Fences works differently to Portals. Stardock Fences actively manipulates your existing Desktop Icons, Portals just shows contents of folders.  Try dragging these items into a folder without using Portals, you cannot do it. So I will not make Portals manipulate desktop icons, that is not its intention.

**Comment by GameIT-Official** [comment] 2022-12-10 12:33
When the portal is placed on top the mouse pointer turns into window
resize mode, I fixed this problem my placing the portals a bit outside of
the desktop, here's the vid:

https://youtu.be/osck7p6PZ6w

Also when I right click on Icons the portals menu opens instead of the default one, is there any way to disable the portals right click menu and just use the default windows one?

BTW ty very much for your replies and awesome software!!

**Comment by Ross-Patterson** [comment] 2022-12-10 13:01
Thanks for the video - I see what you are saying now. I think this is just how a Windows window works - I could try to make the pointer not change if the Portal is locked, but it still would not expand as in this case it seems Windows sees the pointer as outside the Window.

I think your -3y solution is probably the best solution here. You can make the portal header slightly larger if neeeded.

As for the right click menu - there are some technicalities that are stopping me from allowing just the Windows menu. Mainly the Renaming of items. Because the windows menu "Rename" button works only for windows explorer items, it does nothing on items in a Portal and is extremely bloaty to reimplement on the Windows menu. (Windows API programming is awful).

**Comment by GameIT-Official** [comment] 2022-12-10 14:49
Np ty for your assistance! looking forward to the next update!
And one more thing, can I use Portals in one of my videos??

**Closed** 2023-04-21 17:14 UTC
Labels: enhancement, acknowledged
