### ISSUE TITLE
Snap to grid + sticky collapsing

### ISSUE THREAD

**Issue by el-ef** [Ross-Patterson/Portals-Desktop-Organization#32] opened 2022-06-27 12:59 UTC
Hi there,
thank your for developing this wonderful app!

Have you thought about implementing something that would prevent the portals from overlapping each other and snap to an invisible grid for a more uniform look?

Also, as a little extra, it would be awsome if the boxes could attach to each other vertically so that when you fold up one box, the others below would automatically follow and slide up to close the gap.

Keep up the great work!
Regards - el-ef

PS: In case you need a translator for german, just leave me a notice. :)

**Comment by Ross-Patterson** [comment] 2022-07-14 09:29
@el-ef,
 For a grid-like setup, you could try enabling Relative Positioning:
![image](https://user-images.githubusercontent.com/66630787/178950343-a5b86ed3-ec61-491a-9b2f-468f10f0b6f7.png)

This will allow you to set your portals as a percentage of a specific display.

**Note:** currently it doesn't work very well if you are constantly switching between different display setups, or using Display Scaling. (I'm working on that).

On, attaching vertically, this is a duplicate of #18 , due to a Portal being just a window, it would be very hard to stack the windows and have them constantly moving according to other windows positions.

**Closed by Ross-Patterson** 2022-07-14 09:29 UTC
Labels: enhancement
