### ISSUE TITLE
Crash when clicking "No" to User Account Control prompt when opening program from portal window

### ISSUE THREAD

**Issue by jbrunette** [Ross-Patterson/Portals-Desktop-Organization#49] opened 2022-09-04 20:42 UTC
**Describe the bug**
Portals crashes if user clicks No or clicks the X at the top right of the User Account Control dialog that asks "Do you want to allow this app to make changes to your device?"

**To Reproduce**
1. Make sure Windows User Account Control settings are set to at least the second "Always notify" level ("Notify me only when apps...")
3. Add an icon to a portal window for a program that requires administrator permissions (right-click shortcut and select Properties > Shortcut > Advanced... > Run as administrator)
4. Run program from portal window.
5. When User Account Control window opens, click "No".
6. Portal crashes and creates crashlog.

**Expected behavior**
Nothing should happen if user clicks No on User Account Control window.

**Desktop (please complete the following information):**
 - OS: Windows 11

[portals_crashlog_2022-09-04_15-36-27_1851348.log](https://github.com/Ross-Patterson/Portals-Desktop-Organization/files/9485470/portals_crashlog_2022-09-04_15-36-27_1851348.log)

**Comment by Ross-Patterson** [comment] 2022-09-22 09:05
Thanks for uploading the crashlog, this makes it very easy to see what happened. I will add a clause to catch when the user cancels the operation, hopefully for next release.

**Comment by Ross-Patterson** [comment] 2022-10-04 09:33
I want to thank you again for providing the crashlog and also steps to reproduce, I was able to fix in like 10mins because of your clear bug report.

It is now in for the next release.

**Comment by Ross-Patterson** [comment] 2022-10-15 12:29
This is now fixed and available in v2.1.0.6

**Closed by Ross-Patterson** 2022-10-15 12:29 UTC
Labels: bug, acknowledged
