### ISSUE TITLE
Launch shortcuts with one click instead of two

### ISSUE THREAD

**Issue by CinnamonMina** [Ross-Patterson/Portals-Desktop-Organization#152] opened 2023-06-06 03:26 UTC
Its very tedious having to double click to open anything, and its inconsistent between normal desktop and portals if the single click to open items is enabled on Windows Explorer. it would be nice to just have an option on the portal content settings to open things with one click.

**Comment by Ross-Patterson** [comment] 2023-06-07 20:03
Duplicate of #70 

Will be implemented in next release:
![image](https://github.com/Ross-Patterson/Portals-Desktop-Organization/assets/66630787/c0f4c6e2-a95b-40b5-b667-6d4e99864183)

**Closed by Ross-Patterson** 2023-06-07 20:03 UTC
Labels: enhancement
