### ISSUE TITLE
Path edit; sub portals

### ISSUE THREAD

**Issue by Alexnoj** [Ross-Patterson/Portals-Desktop-Organization#63] opened 2022-10-22 07:15 UTC
- option to Path edit.
- option to create sub portals.  (I add img for example)
- 
![image](https://user-images.githubusercontent.com/30004592/197326027-56b81014-69f1-41b3-89d4-cf6a2a57f443.png)

**Comment by Ross-Patterson** [comment] 2022-10-28 09:53
**Path Edit:** I will consider.
**Sub Portals:** Won't Happen (at least in the way you show above) - I am considering "tabbed portals", but that is likely a long way off.

**Comment by Ross-Patterson** [comment] 2023-04-21 17:35
Duplicate of #111

**Closed by Ross-Patterson** 2023-04-21 17:35 UTC
Labels: enhancement, acknowledged
