### ISSUE TITLE
BUG: Executing an application from within a Portal causes the application to be executed from C:\Windows\system32 instead of it's current directory.

### ISSUE THREAD

**Issue by linkgannon** [Ross-Patterson/Portals-Desktop-Organization#311] opened 2024-06-04 15:37 UTC
### Check the Help Site and GitHub Issues/Discussions

- [X] I have checked and found nothing.

### Version

3.2.1.0

### Operating System

Windows 11

### What happened?

I have some .NET console applications (just the raw executables as all the DLLs are embedded) on my desktop. These applications when ran generate a file in the same directory that the application was executed in (just by using relative pathing). If I open up a file explorer and run the app, it works as expected, generating the file in that same directory. However, if I execute it from a Portal, I get the following error: 
`Unhandled Exception: System.UnauthorizedAccessException: Access to the path 'C:\Windows\system32\fileName.csv' is denied.`

This leads me to believe that Portals executes the app from a base directory of C:\Windows\system32 instead of the directory that it's actually in. I would imagine this could cause problems for many applications and scripts that utilize relative pathing.

### Steps to Reproduce

Execute the following batch script from the file explorer, followed by executing it directly from a Portal:
```
SET mypath=%~dp0
echo %mypath:~0,-1%
pause
```

File Explorer Result:
```
C:\Users\username\Desktop>SET mypath=C:\Users\username\Desktop\

C:\Users\username\Desktop>echo C:\Users\username\Desktop
C:\Users\username\Desktop

C:\Users\username\Desktop>pause
Press any key to continue . . .
```

Portal Result:
```
C:\Windows\System32>SET mypath=C:\Users\username\Desktop\

C:\Windows\System32>echo C:\Users\username\Desktop
C:\Users\username\Desktop

C:\Windows\System32>pause
```

### What would you expect to happen?

When executing the sample batch script from the Portal, it should match the result as if you executed it from the File Explorer.

**Comment by Ross-Patterson** [comment] 2024-06-04 20:26
Duplicate of #283, this is fixed in the beta version 3.3.0.5 (you can switch to beta channel in settings).

**Closed by Ross-Patterson** 2024-06-04 20:26 UTC
Labels: bug
