### ISSUE TITLE
Portable version and File Mode

### ISSUE THREAD

**Issue by jimmy123j** [Ross-Patterson/Portals-Desktop-Organization#103] opened 2023-02-21 13:42 UTC
**Is your feature request related to a problem? Please describe.**
1. Portable ver. as literally
2. Hope file into portals box can select origin file and create shortcut, avoid accidentally deleting portal's files

**Describe the solution you'd like**
1. Portable ver. as literally
2. File Mode option with 'origine file' and 'shortcut' after File or Files draged/droped into portals box
    - 3 setting option with File Mode
    -- Confirm Mode ( show 'origine file' and 'shortcut' option after draged/droped File into portals box )
    -- Origine File Mode ( default 'origine file' after draged/droped File into portals box, as now portals does )
    -- Shortcut Mode ( default 'shortcut' after draged/droped File into portals box )

**Describe alternatives you've considered**
N/A

**Additional context**
It's the only fly in the ointment of our marriage of file mode only with origine file, hope can add file mode for user custom
If file mode feature can be imported, I'll support this project
Thanks for App. development, it's great and useful than fences for me
Thanks again !!!

**Comment by Ross-Patterson** [comment] 2023-04-21 17:33
1. Duplicate of #95 
2. Not Planned.

**Closed by Ross-Patterson** 2023-04-21 17:33 UTC
Labels: enhancement
