### ISSUE TITLE
Sort by folder priority on systen load not being respected

### ISSUE THREAD

**Issue by Registered55** [Ross-Patterson/Portals-Desktop-Organization#290] opened 2024-04-25 07:32 UTC
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
create a portal, sort by > folder priority > first
restart windows, when the portals load up with desktop, the FOLDERS are put back into alphabet order, and not respecting the FIRST priority.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 LTSC]
 - Version [e.g. 21H2]

**Additional context**

**Comment by Ross-Patterson** [comment] 2024-04-26 20:50
duplicate of #281 - will be fixed

**Closed by Ross-Patterson** 2024-04-26 20:50 UTC
Labels: bug
